services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: sh -c "cd server && npm run start:dev"

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=data-eng
      - POSTGRES_PASSWORD=031199
      - POSTGRES_USER=root
    expose:
      - 5432
volumes:
  db-data: